INTERACTIVE_MODELS_PATH: "./weights"
EXPS_PATH: "./experiments"

# Evaluation datasets
GRABCUT_PATH: "./datasets/GrabCut"
BERKELEY_PATH: "./datasets/Berkeley"
DAVIS_PATH: "./datasets/DAVIS"
COCO_MVAL_PATH: "./datasets/COCO_MVal"
RETINAL_VAL_PATH: "./datasets/RETINAL_VAL"
ABLATIONZONE_VAL_PATH: "./datasets/AblationZone_VAL"
MSLESION_VAL_PATH: "./datasets/MS_Lesion/val"
IDRID_VAL_PATH: "./datasets/IDRiD_VAL"
DDR_VAL_PATH: "./datasets/DDR_VAL"
HOSPITAL_VAL_PATH: "./datasets/HOSPITAL_VAL"
# Train datasets
SBD_PATH: "./datasets/SBD"
COCO_PATH: "./datasets/coco2017"
LVIS_PATH: "./datasets/LVIS"
OPENIMAGES_PATH: "./datasets/OpenImages"
PASCALVOC_PATH: "./datasets/PascalVOC"
ADE20K_PATH: "./datasets/ADE20K"
LVIS_v1_PATH: "./datasets/COCO+LVIS"
RETINAL_PATH: "./datasets/RETINAL"
ABLATIONZONE_TRAIN_PATH: "./datasets/AblationZone_TRAIN"
MSLESION_TRAIN_PATH: "./datasets/MS_Lesion/train"

# Test datasets
ABLATIONZONE_TEST_PATH: "./datasets/AblationZone_TEST"


# You can download the weights for HRNet from the repository:
# https://github.com/HRNet/HRNet-Image-Classification
IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18: "./pretrained_models/hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W32: "./pretrained_models/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W40: "./pretrained_models/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "./pretrained_models/hrnetv2_w48_imagenet_pretrained.pth"
  HRNETV2_W18_SMALL: "./pretrained_models/hrnet_w18_small_model_v2.pth"
